  global:
  root_path: "/mnt/parscratch/users/acp21rjf/spotify/long_only/FT_3epoch/"
  name: rotary_pos_6l_768d_pre_windowed_longonly_spotify
  seq_len: 360000
  checkpoint: step_23763.pt
  overlap_ratio: 0.875
  description: "Finetuning (on spotify with 10K longest recordings) + eval with windowed attention at fixed seq len and varying window sizes (reduced steps)"
  downsampling: 8

models:
 
  - name: ${global.name}
    repeat: 1
    window_size: 128
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio} 
    path: ${global.root_path}spotify-L-FT-w${.window_size}-5e5-rp-${.repeat}/${global.checkpoint}
  - name: ${global.name}
    repeat: 2
    window_size: 128
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}spotify-L-FT-w${.window_size}-5e5-rp-${.repeat}/${global.checkpoint}
  - name: ${global.name}  
    repeat: 3
    window_size: 128
    seq_len: ${global.seq_len}
    overlap_ratio: 0.875
    path: ${global.root_path}spotify-L-FT-w${.window_size}-5e5-rp-${.repeat}/${global.checkpoint}


  - name: ${global.name}
    repeat: 1
    window_size: 512
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}spotify-L-FT-w${.window_size}-5e5-rp-${.repeat}/${global.checkpoint}
   
  - name: ${global.name}
    repeat: 2
    window_size: 512
    seq_len: ${global.seq_len}
    overlap_ratio: 0.875
    path: ${global.root_path}spotify-L-FT-w${.window_size}-5e5-rp-${.repeat}/${global.checkpoint}
   
  - name: ${global.name} 
    repeat: 3
    window_size: 512
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}spotify-L-FT-w${.window_size}-5e5-rp-${.repeat}/${global.checkpoint}
   


  - name: ${global.name}
    repeat: 1
    window_size: 2048
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}spotify-L-FT-w${.window_size}-5e5-rp-${.repeat}/${global.checkpoint}
   
  - name: ${global.name}
    repeat: 2
    window_size: 2048
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}spotify-L-FT-w${.window_size}-5e5-rp-${.repeat}/${global.checkpoint}
    
  - name: ${global.name}
    repeat: 3
    window_size: 2048
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}spotify-L-FT-w${.window_size}-5e5-rp-${.repeat}/${global.checkpoint}
  


  - name: ${global.name}
    repeat: 1
    window_size: 8192
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}spotify-L-FT-w${.window_size}-5e5-rp-${.repeat}/${global.checkpoint}
    
  - name: ${global.name}
    repeat: 2
    window_size: 8192
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}spotify-L-FT-w${.window_size}-5e5-rp-${.repeat}/${global.checkpoint}
    
  - name: ${global.name} # Not finished!!
    repeat: 3
    window_size: 8192
    seq_len: ${global.seq_len}
    overlap_ratio: 0.875
    path: ${global.root_path}spotify-L-FT-w${.window_size}-5e5-rp-${.repeat}/${global.checkpoint}


  - name: ${global.name}
    repeat: 1
    window_size: 22500
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}spotify-L-FT-w${.window_size}-5e5-rp-${.repeat}/${global.checkpoint}
   
  - name: ${global.name}
    repeat: 2
    window_size: 22500
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}spotify-L-FT-w${.window_size}-5e5-rp-${.repeat}/${global.checkpoint}
   
  - name: ${global.name}
    repeat: 3
    window_size: 22500
    seq_len: ${global.seq_len}
    overlap_ratio: 0.875
    path: ${global.root_path}spotify-L-FT-w${.window_size}-5e5-rp-${.repeat}/${global.checkpoint}




args:
  verbose: true
  model_class: SCConformerXL
  evaluation_mode: windowed_attention
  max_sequence_length: 3600000
  save_dataframe_path: './results/thesis/long_only_FT_3epoch_5e5.csv'
  # include_per_recording_evaluations: true
  # tokenizer_path: "/users/acp21rjf/long-context-asr/lcasr/artifacts/floras50/tokenizer.model"
  # run_eval_with: concat_tedlium_eval

datasets:
  - name: tedlium
    splits: [test]
    args:
      single_utterance: false
      concat: false
  - name: rev16
    splits: [test]
  - name: earnings22_full
    splits: [test]
  - name: this_american_life
    splits: [test]
  - name: earnings22
    splits: [test]