global:
  root_path: "/mnt/parscratch/users/acp21rjf/spotify/long_only/FT_3epoch_18L/"
  name: rotary_pos_18l_1024d_longonly_ft_spotify
  seq_len: 360000
  checkpoint: step_23763.pt
  overlap_ratio: 0.875
  description: "18L 1024D model finetuned for 3 epochs on Spotify long-only data; evaluated with fixed 1h chunks and windowed attention"
  downsampling: 8

models:
  - name: ${global.name}
    repeat: 1
    window_size: 128
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}spotify-L-FT-w${.window_size}-5e5-rp-${.repeat}/${global.checkpoint}
    description: ${global.description}
  - name: ${global.name}
    repeat: 2
    window_size: 128
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}spotify-L-FT-w${.window_size}-5e5-rp-${.repeat}/${global.checkpoint}
    description: ${global.description}
  - name: ${global.name}
    repeat: 3
    window_size: 128
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}spotify-L-FT-w${.window_size}-5e5-rp-${.repeat}/${global.checkpoint}
    description: ${global.description}

  - name: ${global.name}
    repeat: 1
    window_size: 512
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}spotify-L-FT-w${.window_size}-5e5-rp-${.repeat}/${global.checkpoint}
    description: ${global.description}
  - name: ${global.name}
    repeat: 2
    window_size: 512
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}spotify-L-FT-w${.window_size}-5e5-rp-${.repeat}/${global.checkpoint}
    description: ${global.description}
  - name: ${global.name}
    repeat: 3
    window_size: 512
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}spotify-L-FT-w${.window_size}-5e5-rp-${.repeat}/${global.checkpoint}
    description: ${global.description}

  - name: ${global.name}
    repeat: 1
    window_size: 2048
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}spotify-L-FT-w${.window_size}-5e5-rp-${.repeat}/${global.checkpoint}
    description: ${global.description}
  - name: ${global.name}
    repeat: 2
    window_size: 2048
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}spotify-L-FT-w${.window_size}-5e5-rp-${.repeat}/${global.checkpoint}
    description: ${global.description}
  - name: ${global.name}
    repeat: 3
    window_size: 2048
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}spotify-L-FT-w${.window_size}-5e5-rp-${.repeat}/${global.checkpoint}
    description: ${global.description}

  - name: ${global.name}
    repeat: 1
    window_size: 8192
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}spotify-L-FT-w${.window_size}-5e5-rp-${.repeat}/${global.checkpoint}
    description: ${global.description}
  - name: ${global.name}
    repeat: 2
    window_size: 8192
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}spotify-L-FT-w${.window_size}-5e5-rp-${.repeat}/${global.checkpoint}
    description: ${global.description}
  - name: ${global.name}
    repeat: 3
    window_size: 8192
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}spotify-L-FT-w${.window_size}-5e5-rp-${.repeat}/${global.checkpoint}
    description: ${global.description}

  - name: ${global.name}
    repeat: 1
    window_size: 22500
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}spotify-L-FT-w${.window_size}-5e5-rp-${.repeat}/${global.checkpoint}
    description: ${global.description}
  - name: ${global.name}
    repeat: 2
    window_size: 22500
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}spotify-L-FT-w${.window_size}-5e5-rp-${.repeat}/${global.checkpoint}
    description: ${global.description}
  - name: ${global.name}
    repeat: 3
    window_size: 22500
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}spotify-L-FT-w${.window_size}-5e5-rp-${.repeat}/${global.checkpoint}
    description: ${global.description}

args:
  verbose: false
  model_class: SCConformerXL
  evaluation_mode: windowed_attention
  max_sequence_length: 3600000
  save_dataframe_path: './results/thesis/long_only_FT_3epoch_18L_5e5.csv'

datasets:
  - name: tedlium
    splits: [test]
    args:
      single_utterance: false
      concat: false
  - name: rev16
    splits: [test]
  - name: earnings22_full
    splits: [test]
  - name: this_american_life
    splits: [test]
  - name: earnings22
    splits: [test]
