models:
  - name: rb_sp2
    repeat: 1
    seq_len: 4096
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_spec_freq2/n_seq_sched_4096_rp_1/step_105360.pt
    description: "rotary base set to 1.5M and (specaugment) 3 frequency masks with width of 18 (setting 2)"
  - name: rb_sp2
    repeat: 2
    seq_len: 4096
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_spec_freq2/n_seq_sched_4096_rp_2/step_105360.pt
    description: "rotary base set to 1.5M and (specaugment) 3 frequency masks with width of 18 (setting 2)"
  - name: rb_sp2
    repeat: 3
    seq_len: 4096
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_spec_freq2/n_seq_sched_4096_rp_3/step_105360.pt
    description: "rotary base set to 1.5M and (specaugment) 3 frequency masks with width of 18 (setting 2)"

  - name: rb_sp2
    repeat: 1
    seq_len: 8192
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_spec_freq2/n_seq_sched_8192_rp_1/step_105360.pt
    description: "rotary base set to 1.5M and (specaugment) 3 frequency masks with width of 18 (setting 2)"
  - name: rb_sp2
    repeat: 2
    seq_len: 8192
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_spec_freq2/n_seq_sched_8192_rp_2/step_105360.pt
    description: "rotary base set to 1.5M and (specaugment) 3 frequency masks with width of 18 (setting 2)"
  - name: rb_sp2
    repeat: 3
    seq_len: 8192
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_spec_freq2/n_seq_sched_8192_rp_3/step_105360.pt
    description: "rotary base set to 1.5M and (specaugment) 3 frequency masks with width of 18 (setting 2)"

  - name: rb_sp2
    repeat: 1
    seq_len: 16384
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_spec_freq2/n_seq_sched_16384_rp_1/step_105360.pt
    description: "rotary base set to 1.5M and (specaugment) 3 frequency masks with width of 18 (setting 2)"
  - name: rb_sp2
    repeat: 2
    seq_len: 16384
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_spec_freq2/n_seq_sched_16384_rp_2/step_105360.pt
    description: "rotary base set to 1.5M and (specaugment) 3 frequency masks with width of 18 (setting 2)"
  - name: rb_sp2
    repeat: 3
    seq_len: 16384
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_spec_freq2/n_seq_sched_16384_rp_3/step_105360.pt
    description: "rotary base set to 1.5M and (specaugment) 3 frequency masks with width of 18 (setting 2)"

  - name: rb_sp2
    repeat: 1
    seq_len: 32768
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_spec_freq2/n_seq_sched_32768_rp_1/step_105360.pt
    description: "rotary base set to 1.5M and (specaugment) 3 frequency masks with width of 18 (setting 2)"
  - name: rb_sp2
    repeat: 2
    seq_len: 32768
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_spec_freq2/n_seq_sched_32768_rp_2/step_105360.pt
    description: "rotary base set to 1.5M and (specaugment) 3 frequency masks with width of 18 (setting 2)"
  - name: rb_sp2
    repeat: 3
    seq_len: 32768
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_spec_freq2/n_seq_sched_32768_rp_3/step_105360.pt
    description: "rotary base set to 1.5M and (specaugment) 3 frequency masks with width of 18 (setting 2)"

  - name: rb_sp2
    repeat: 1
    seq_len: 65536
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_spec_freq2/n_seq_sched_65536_rp_1/step_105360.pt
    description: "rotary base set to 1.5M and (specaugment) 3 frequency masks with width of 18 (setting 2)"
  - name: rb_sp2
    repeat: 2
    seq_len: 65536
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_spec_freq2/n_seq_sched_65536_rp_2/step_105360.pt
    description: "rotary base set to 1.5M and (specaugment) 3 frequency masks with width of 18 (setting 2)"
  - name: rb_sp2
    repeat: 3
    seq_len: 65536
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_spec_freq2/n_seq_sched_65536_rp_3/step_105360.pt
    description: "rotary base set to 1.5M and (specaugment) 3 frequency masks with width of 18 (setting 2)"

  - name: rb_sp2
    repeat: 1
    seq_len: 360000
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_spec_freq2/n_seq_sched_360000_rp_1/step_105360.pt
    description: "rotary base set to 1.5M and (specaugment) 3 frequency masks with width of 18 (setting 2)"
  - name: rb_sp2
    repeat: 2
    seq_len: 360000
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_spec_freq2/n_seq_sched_360000_rp_2/step_105360.pt
    description: "rotary base set to 1.5M and (specaugment) 3 frequency masks with width of 18 (setting 2)"
  - name: rb_sp2
    repeat: 3
    seq_len: 360000
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_spec_freq2/n_seq_sched_360000_rp_3/step_105360.pt
    description: "rotary base set to 1.5M and (specaugment) 3 frequency masks with width of 18 (setting 2)"


args:
  splits: [dev, test]
  datasets: [earnings22, tedlium, rev16]
  single_utterance: false # only used on some datasets i.e tedlium
  verbose: true
  model_class: SCConformerXL
  save_dataframe_path: './results/evals_rb_sp2.csv'