models:
  # - name: rb_10M_n_seq_sched
  #   repeat: 1
  #   seq_len: 131072
  #   overlap_ratio: 0.875
  #   path: /mnt/parscratch/users/acp21rjf/spotify/rotary_pos_10M_seq_sched/n_seq_sched_131072_rp_1/step_105360.pt
  #   description: "looking at setting rotary base frequency to 10M and varying the sequence length"
  - name: rb_10M_n_seq_sched
    repeat: 2
    seq_len: 131072
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/rotary_pos_10M_seq_sched/n_seq_sched_131072_rp_2/step_105360.pt
    description: "looking at setting rotary base frequency to 10M and varying the sequence length"  
  - name: rb_10M_n_seq_sched
    repeat: 3
    seq_len: 131072
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/rotary_pos_10M_seq_sched/n_seq_sched_131072_rp_3/step_105360.pt
    description: "looking at setting rotary base frequency to 10M and varying the sequence length"

  # - name: rb_10M_n_seq_sched
  #   repeat: 1
  #   seq_len: 262144
  #   overlap_ratio: 0.875
  #   path: /mnt/parscratch/users/acp21rjf/spotify/rotary_pos_10M_seq_sched/n_seq_sched_262144_rp_1/step_105360.pt
  #   description: "looking at setting rotary base frequency to 10M and varying the sequence length"
  # - name: rb_10M_n_seq_sched
  #   repeat: 2
  #   seq_len: 262144
  #   overlap_ratio: 0.875
  #   path: /mnt/parscratch/users/acp21rjf/spotify/rotary_pos_10M_seq_sched/n_seq_sched_262144_rp_2/step_105360.pt
  #   description: "looking at setting rotary base frequency to 10M and varying the sequence length"  
  # - name: rb_10M_n_seq_sched
  #   repeat: 3
  #   seq_len: 262144
  #   overlap_ratio: 0.875
  #   path: /mnt/parscratch/users/acp21rjf/spotify/rotary_pos_10M_seq_sched/n_seq_sched_262144_rp_3/step_105360.pt
  #   description: "looking at setting rotary base frequency to 10M and varying the sequence length"

  - name: rb_10M_n_seq_sched
    repeat: 1
    seq_len: 360000
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/rotary_pos_10M_seq_sched/n_seq_sched_360000_rp_1/step_105360.pt
    description: "looking at setting rotary base frequency to 10M and varying the sequence length"
  - name: rb_10M_n_seq_sched
    repeat: 2
    seq_len: 360000
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/rotary_pos_10M_seq_sched/n_seq_sched_360000_rp_2/step_105360.pt
    description: "looking at setting rotary base frequency to 10M and varying the sequence length"  
  - name: rb_10M_n_seq_sched
    repeat: 3
    seq_len: 360000
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/rotary_pos_10M_seq_sched/n_seq_sched_360000_rp_3/step_105360.pt
    description: "looking at setting rotary base frequency to 10M and varying the sequence length"

args:
  splits: [test]
  datasets: [earnings22_full]
  single_utterance: false # only used on some datasets i.e tedlium
  verbose: true
  model_class: SCConformerXL
  save_dataframe_path: './results/evals_rb_10M.csv'