models:
  - name: wd_n_seq_sched_2048
    repeat: 1
    seq_len: 2048
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_wd/n_seq_sched_2048_rp_1/step_105360.pt
    description: "trained with weight decay and sequence length of 2048"
  # - name: wd_n_seq_sched_2048
  #   repeat: 2
  #   seq_len: 2048
  #   overlap_ratio: 0.875
  #   path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_wd/n_seq_sched_2048_rp_2/step_105360.pt
  #   description: "trained with weight decay and sequence length of 2048"
  # - name: wd_n_seq_sched_2048
  #   repeat: 3
  #   seq_len: 2048
  #   overlap_ratio: 0.875
  #   path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_wd/n_seq_sched_2048_rp_3/step_105360.pt
  #   description: "trained with weight decay and sequence length of 2048"

  - name: rb_wd_n_seq_sched_2048
    repeat: 1
    seq_len: 2048
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_wd/n_seq_sched_2048_rp_1/step_105360.pt
    description: "trained with weight decay and sequence length of 2048 rotary base frequency increased to 1.5M from default 10k"
  - name: rb_wd_n_seq_sched_2048
    repeat: 2
    seq_len: 2048
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_wd/n_seq_sched_2048_rp_2/step_105360.pt
    description: "trained with weight decay and sequence length of 2048 rotary base frequency increased to 1.5M from default 10k"
  - name: rb_wd_n_seq_sched_2048
    repeat: 3
    seq_len: 2048
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_wd/n_seq_sched_2048_rp_3/step_105360.pt
    description: "trained with weight decay and sequence length of 2048 rotary base frequency increased to 1.5M from default 10k"

  - name: wd_n_seq_sched_8192
    repeat: 1
    seq_len: 8192
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_wd/n_seq_sched_8192_rp_1/step_105360.pt
    description: "trained with weight decay and sequence length of 8192"
  - name: wd_n_seq_sched_8192
    repeat: 2
    seq_len: 8192
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_wd/n_seq_sched_8192_rp_2/step_105360.pt
    description: "trained with weight decay and sequence length of 8192"
  - name: wd_n_seq_sched_8192
    repeat: 3
    seq_len: 8192
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_wd/n_seq_sched_8192_rp_3/step_105360.pt
    description: "trained with weight decay and sequence length of 8192"
  - name: rb_wd_n_seq_sched_8192

    repeat: 1
    seq_len: 8192
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_wd/n_seq_sched_8192_rp_1/step_105360.pt
    description: "trained with weight decay and sequence length of 8192 rotary base frequency increased to 1.5M from default 10k"
  - name: rb_wd_n_seq_sched_8192
    repeat: 2
    seq_len: 8192
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_wd/n_seq_sched_8192_rp_2/step_105360.pt
    description: "trained with weight decay and sequence length of 8192 rotary base frequency increased to 1.5M from default 10k"
  - name: rb_wd_n_seq_sched_8192
    repeat: 3
    seq_len: 8192
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_wd/n_seq_sched_8192_rp_3/step_105360.pt
    description: "trained with weight decay and sequence length of 8192 rotary base frequency increased to 1.5M from default 10k"


  - name: wd_n_seq_sched_4096
    repeat: 1
    seq_len: 4096
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_wd/n_seq_sched_4096_rp_1/step_105360.pt
    description: "trained with weight decay and sequence length of 4096"
  # - name: wd_n_seq_sched_4096
  #   repeat: 2
  #   seq_len: 4096
  #   overlap_ratio: 0.875
  #   path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_wd/n_seq_sched_4096_rp_2/step_105360.pt
  #   description: "trained with weight decay and sequence length of 4096"
  - name: wd_n_seq_sched_4096
    repeat: 3
    seq_len: 4096
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_wd/n_seq_sched_4096_rp_3/step_105360.pt
    description: "trained with weight decay and sequence length of 4096"

  - name: rb_wd_n_seq_sched_4096
    repeat: 1
    seq_len: 4096
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_wd/n_seq_sched_4096_rp_1/step_105360.pt
    description: "trained with weight decay and sequence length of 4096 rotary base frequency increased to 1.5M from default 10k"
  - name: rb_wd_n_seq_sched_4096
    repeat: 2
    seq_len: 4096
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_wd/n_seq_sched_4096_rp_2/step_105360.pt
    description: "trained with weight decay and sequence length of 4096 rotary base frequency increased to 1.5M from default 10k"
  - name: rb_wd_n_seq_sched_4096
    repeat: 3
    seq_len: 4096
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_wd/n_seq_sched_4096_rp_3/step_105360.pt
    description: "trained with weight decay and sequence length of 4096 rotary base frequency increased to 1.5M from default 10k"


  - name: wd_n_seq_sched_16384
    repeat: 1
    seq_len: 16384
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_wd/n_seq_sched_16384_rp_1/step_105360.pt
    description: "trained with weight decay and sequence length of 16384"
  - name: wd_n_seq_sched_16384
    repeat: 2
    seq_len: 16384
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_wd/n_seq_sched_16384_rp_2/step_105360.pt
    description: "trained with weight decay and sequence length of 16384"
  # - name: wd_n_seq_sched_16384
  #   repeat: 3
  #   seq_len: 16384
  #   overlap_ratio: 0.875
  #   path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_wd/n_seq_sched_16384_rp_3/step_105360.pt
  #   description: "trained with weight decay and sequence length of 16384"
  # - name: rb_wd_n_seq_sched_16384
  #   repeat: 1
  #   seq_len: 16384
  #   overlap_ratio: 0.875
  #   path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_wd/n_seq_sched_16384_rp_1/step_105360.pt
  #   description: "trained with weight decay and sequence length of 16384 rotary base frequency increased to 1.5M from default 10k"
  - name: rb_wd_n_seq_sched_16384
    repeat: 2
    seq_len: 16384
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_wd/n_seq_sched_16384_rp_2/step_105360.pt
    description: "trained with weight decay and sequence length of 16384 rotary base frequency increased to 1.5M from default 10k"
  - name: rb_wd_n_seq_sched_16384
    repeat: 3
    seq_len: 16384
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_wd/n_seq_sched_16384_rp_3/step_105360.pt
    description: "trained with weight decay and sequence length of 16384 rotary base frequency increased to 1.5M from default 10k"

  - name: wd_n_seq_sched_32768
    repeat: 1
    seq_len: 32768
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_wd/n_seq_sched_32768_rp_1/step_105360.pt
    description: "trained with weight decay and sequence length of 32768"
  - name: wd_n_seq_sched_32768
    repeat: 2
    seq_len: 32768
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_wd/n_seq_sched_32768_rp_2/step_105360.pt
    description: "trained with weight decay and sequence length of 32768"
  # - name: wd_n_seq_sched_32768
  #   repeat: 3
  #   seq_len: 32768
  #   overlap_ratio: 0.875
  #   path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_wd/n_seq_sched_32768_rp_3/step_105360.pt
  #   description: "trained with weight decay and sequence length of 32768"
  - name: rb_wd_n_seq_sched_32768
    repeat: 1
    seq_len: 32768
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_wd/n_seq_sched_32768_rp_1/step_105360.pt
    description: "trained with weight decay and sequence length of 32768 rotary base frequency increased to 1.5M from default 10k"
  - name: rb_wd_n_seq_sched_32768
    repeat: 2
    seq_len: 32768
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_wd/n_seq_sched_32768_rp_2/step_105360.pt
    description: "trained with weight decay and sequence length of 32768 rotary base frequency increased to 1.5M from default 10k"
  - name: rb_wd_n_seq_sched_32768
    repeat: 3
    seq_len: 32768
    overlap_ratio: 0.875
    path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_wd/n_seq_sched_32768_rp_3/step_105360.pt
    description: "trained with weight decay and sequence length of 32768 rotary base frequency increased to 1.5M from default 10k"



args:
  splits: [dev, test]
  datasets: [earnings22, tedlium, rev16]
  single_utterance: false # only used on some datasets i.e tedlium
  verbose: true
  model_class: SCConformerXL
  save_dataframe_path: './results/evals.csv'