
model:
  feat_in: 80
  n_layers: 12
  d_model: 256
  n_heads: 8
  head_dim: 32
  dropout_ff: 0.0
  dropout_attn: 0.0
  dropout_conv: 0.0
  checkpoint_every_n_layers: 0
  subsampling_factor: 4
  conv_kernel_size: 31

optimizer:
  lr: 4e-6
  betas: [0.9, 0.98]
  eps: 1e-6

scheduler:
  warmup_steps: 1

audio_chunking:
  size: 12288
  overlap: 0

wandb:
  use: true
  project_name: "spotify_long_context"
  id: "" # leave empty if not resuming a previous run

  