model:
  feat_in: 80
  n_layers: 6
  d_model: 768
  n_heads: 6
  head_dim: 128
  dropout_ff: 0.0
  dropout_attn: 0.0
  dropout_conv: 0.0
  checkpoint_every_n_layers: 0
  subsampling_factor: 8
  subsampling: dw_striding
  subsampling_conv_channels: 256
  conv_kernel_size: 9
  qk_rms_norm: false
  shift_kvs: false
  self_conditioning: true
  gated_sc: false
  decoder_norm: true
  use_rotary: true
  encoder_mode: conformer
  history_vector: false
  default_norm: layer_norm
optimizer:
  name: madgrad
  args:
    lr: 0.0001
scheduler:
  warmup_steps: 3000
audio_chunking:
  size: 1024
  overlap: 0
wandb:
  use: true
  project_name: spotify_long_context
  name: 1024_1e4_cache_1024
  id: ''
checkpointing:
  dir: /mnt/parscratch/users/acp21rjf/1024_1e4_cache_1024
  save_every_n_steps: 25
data:
  path: /mnt/parscratch/users/acp21rjf/spotify/audio_txt_pairs.json
training:
  batch_size: 352
  backprop_every: 1
  max_seq_len: 1024
