model:
  feat_in: 80
  n_layers: 6
  d_model: 768
  n_heads: 6
  head_dim: 128
  dropout_ff: 0.0
  dropout_attn: 0.0
  dropout_conv: 0.0
  subsampling_factor: 12
  subsampling: dw_striding
  subsampling_act: silu
  subsampling_conv_channels: 256
  self_condition_subsampling: false
  subsampling_norm_out: false
  conv_kernel_size: 9
  qk_rms_norm: false
  shift_kvs: false
  self_conditioning: true
  gated_sc: false
  decoder_norm: true
  use_rotary: true
  encoder_mode: conformer
  default_norm: rms_norm
  sandwich_norm: false
  bias_in_ff: false
  checkpoint_every_n_layers: 0
  grouped_attention: true
optimizer:
  name: madgrad
  args:
    lr: 0.001
scheduler:
  warmup_steps: 9000
audio_chunking:
  size: 4092
  overlap: 0
wandb:
  use: true
  project_name: spotify_long_context
  name: fc12x_4092_1e3
  id: ''
checkpointing:
  dir: /mnt/parscratch/users/acp21rjf/spotify/checkpoints/fc12x_4092_1e3
  save_every_n_steps: 2000
data:
  path: /mnt/parscratch/users/acp21rjf/spotify/audio_txt_pairs.json
training:
  batch_size: 44
  backprop_every: 2
  backwards_every: 1
  max_seq_len: 0
  clip_value: 0.8
  intermediate_loss_weighting: 0.0
