template_info:
  create: 30 # number of experiments to create
  include_keys: [
    'model', 
    'optimizer', 
    'scheduler', 
    'audio_chunking', 
    'wandb', 
    'checkpointing', 
    'data', 
    'training', 
    'description',
    'model_class',
    'sequence_scheduler',
    'spec_augment'
  ] # keys to include in experiments config
  template_keys: [
    'checkpointing.dir', 
    'wandb.name', 
    'sequence_scheduler.max_sequence_length',
    'training.random_seed'
  ] # keys to use to create experiments

model_class: 'SCConformerXL'
description: "Here we are looking at using spec augment (frequency and time masking) while using fourier positional encodings"

model:
  feat_in: 80
  n_layers: 6
  d_model: 768
  n_heads: 6
  head_dim: 128
  dropout_ff: 0.0 # dropout parameters
  dropout_attn: 0.0
  dropout_conv: 0.0
  subsampling_factor: 8 # subsampling parameters
  subsampling: 'dw_striding'
  subsampling_act: 'silu'
  subsampling_conv_channels: 256
  self_condition_subsampling: false
  subsampling_norm_out: false
  conv_kernel_size: 9
  qk_rms_norm: false 
  shift_kvs: false
  self_conditioning: true
  gated_sc: false
  decoder_norm: true
  use_rotary: false
  fourier_pos_enc: true
  encoder_mode: 'conformer'
  default_norm: 'layer_norm'
  sandwich_norm: false
  bias_in_ff: false 
  checkpoint_every_n_layers: 0

optimizer:
  name: 'madgrad'
  args:
    lr: 3e-3

scheduler:
  warmup_steps: 1500

audio_chunking: # 360000 (max = 1 hour)
  size: 512
  overlap: 0 # not using currently...

sequence_scheduler:
  increase_every: 5000
  stop_after: 90000
  start_after: 0
  max_sequence_length: [
    1024,
    1024,
    1024,
    2048,
    2048,
    2048,
    4096,
    4096,
    4096,
    8192,
    8192,
    8192,
    16384,
    16384,
    16384,
    32768,
    32768,
    32768,
    65536,
    65536,
    65536,
    131072,
    131072,
    131072,
    262144,
    262144,
    262144,
    360000,
    360000,
    360000,
  ]
  increase_by_multiplier: 2
  batch_size_multiplier: 0.5
  interpolate_rotary: false

wandb:
  use: true
  project_name: "spotify_long_context"
  name: [ 
    'fourier_pos_spec1_n_seq_sched_1024_rp_1',
    'fourier_pos_spec1_n_seq_sched_1024_rp_2',
    'fourier_pos_spec1_n_seq_sched_1024_rp_3',
    'fourier_pos_spec1_n_seq_sched_2048_rp_1',
    'fourier_pos_spec1_n_seq_sched_2048_rp_2',
    'fourier_pos_spec1_n_seq_sched_2048_rp_3',
    'fourier_pos_spec1_n_seq_sched_4096_rp_1',
    'fourier_pos_spec1_n_seq_sched_4096_rp_2',
    'fourier_pos_spec1_n_seq_sched_4096_rp_3',
    'fourier_pos_spec1_n_seq_sched_8192_rp_1',
    'fourier_pos_spec1_n_seq_sched_8192_rp_2',
    'fourier_pos_spec1_n_seq_sched_8192_rp_3',
    'fourier_pos_spec1_n_seq_sched_16384_rp_1',
    'fourier_pos_spec1_n_seq_sched_16384_rp_2',
    'fourier_pos_spec1_n_seq_sched_16384_rp_3',
    'fourier_pos_spec1_n_seq_sched_32768_rp_1',
    'fourier_pos_spec1_n_seq_sched_32768_rp_2',
    'fourier_pos_spec1_n_seq_sched_32768_rp_3',
    'fourier_pos_spec1_n_seq_sched_65536_rp_1',
    'fourier_pos_spec1_n_seq_sched_65536_rp_2',
    'fourier_pos_spec1_n_seq_sched_65536_rp_3',
    'fourier_pos_spec1_n_seq_sched_131072_rp_1',
    'fourier_pos_spec1_n_seq_sched_131072_rp_2',
    'fourier_pos_spec1_n_seq_sched_131072_rp_3',
    'fourier_pos_spec1_n_seq_sched_262144_rp_1',
    'fourier_pos_spec1_n_seq_sched_262144_rp_2',
    'fourier_pos_spec1_n_seq_sched_262144_rp_3',
    'fourier_pos_spec1_n_seq_sched_360000_rp_1',
    'fourier_pos_spec1_n_seq_sched_360000_rp_2',
    'fourier_pos_spec1_n_seq_sched_360000_rp_3',
  ]
  id: "" # leave empty if not resuming a previous run

checkpointing:
  dir: [
    '/mnt/parscratch/users/acp21rjf/spotify/fourier_pos_spec1_seq_sched/n_seq_sched_1024_rp_1',
    '/mnt/parscratch/users/acp21rjf/spotify/fourier_pos_spec1_seq_sched/n_seq_sched_1024_rp_2',
    '/mnt/parscratch/users/acp21rjf/spotify/fourier_pos_spec1_seq_sched/n_seq_sched_1024_rp_3',
    '/mnt/parscratch/users/acp21rjf/spotify/fourier_pos_spec1_seq_sched/n_seq_sched_2048_rp_1',
    '/mnt/parscratch/users/acp21rjf/spotify/fourier_pos_spec1_seq_sched/n_seq_sched_2048_rp_2',
    '/mnt/parscratch/users/acp21rjf/spotify/fourier_pos_spec1_seq_sched/n_seq_sched_2048_rp_3',
    '/mnt/parscratch/users/acp21rjf/spotify/fourier_pos_spec1_seq_sched/n_seq_sched_4096_rp_1',
    '/mnt/parscratch/users/acp21rjf/spotify/fourier_pos_spec1_seq_sched/n_seq_sched_4096_rp_2',
    '/mnt/parscratch/users/acp21rjf/spotify/fourier_pos_spec1_seq_sched/n_seq_sched_4096_rp_3',
    '/mnt/parscratch/users/acp21rjf/spotify/fourier_pos_spec1_seq_sched/n_seq_sched_8192_rp_1',
    '/mnt/parscratch/users/acp21rjf/spotify/fourier_pos_spec1_seq_sched/n_seq_sched_8192_rp_2',
    '/mnt/parscratch/users/acp21rjf/spotify/fourier_pos_spec1_seq_sched/n_seq_sched_8192_rp_3',
    '/mnt/parscratch/users/acp21rjf/spotify/fourier_pos_spec1_seq_sched/n_seq_sched_16384_rp_1',
    '/mnt/parscratch/users/acp21rjf/spotify/fourier_pos_spec1_seq_sched/n_seq_sched_16384_rp_2',
    '/mnt/parscratch/users/acp21rjf/spotify/fourier_pos_spec1_seq_sched/n_seq_sched_16384_rp_3',
    '/mnt/parscratch/users/acp21rjf/spotify/fourier_pos_spec1_seq_sched/n_seq_sched_32768_rp_1',
    '/mnt/parscratch/users/acp21rjf/spotify/fourier_pos_spec1_seq_sched/n_seq_sched_32768_rp_2',  
    '/mnt/parscratch/users/acp21rjf/spotify/fourier_pos_spec1_seq_sched/n_seq_sched_32768_rp_3',
    '/mnt/parscratch/users/acp21rjf/spotify/fourier_pos_spec1_seq_sched/n_seq_sched_65536_rp_1',
    '/mnt/parscratch/users/acp21rjf/spotify/fourier_pos_spec1_seq_sched/n_seq_sched_65536_rp_2',
    '/mnt/parscratch/users/acp21rjf/spotify/fourier_pos_spec1_seq_sched/n_seq_sched_65536_rp_3',
    '/mnt/parscratch/users/acp21rjf/spotify/fourier_pos_spec1_seq_sched/n_seq_sched_131072_rp_1',
    '/mnt/parscratch/users/acp21rjf/spotify/fourier_pos_spec1_seq_sched/n_seq_sched_131072_rp_2',
    '/mnt/parscratch/users/acp21rjf/spotify/fourier_pos_spec1_seq_sched/n_seq_sched_131072_rp_3',
    '/mnt/parscratch/users/acp21rjf/spotify/fourier_pos_spec1_seq_sched/n_seq_sched_262144_rp_1',
    '/mnt/parscratch/users/acp21rjf/spotify/fourier_pos_spec1_seq_sched/n_seq_sched_262144_rp_2',
    '/mnt/parscratch/users/acp21rjf/spotify/fourier_pos_spec1_seq_sched/n_seq_sched_262144_rp_3',
    '/mnt/parscratch/users/acp21rjf/spotify/fourier_pos_spec1_seq_sched/n_seq_sched_360000_rp_1',
    '/mnt/parscratch/users/acp21rjf/spotify/fourier_pos_spec1_seq_sched/n_seq_sched_360000_rp_2',
    '/mnt/parscratch/users/acp21rjf/spotify/fourier_pos_spec1_seq_sched/n_seq_sched_360000_rp_3',
  ]
  save_every_n_steps: 2000

# full data: #'/mnt/parscratch/users/acp21rjf/spotify/audio_txt_pairs.json'
# 25% of corpus: '/users/acp21rjf/long-context-asr/reduced_pairs.json'
data:
  path: '/mnt/parscratch/users/acp21rjf/spotify/audio_txt_pairs.json'
  
spec_augment:
  n_time_masks: 5 # Number of time masks. If its value is zero, no time masking will be applied 
  time_mask_param: -1 # Maximum possible length of the time mask if it is set to -1, min_p is used
  n_freq_masks: 3 # Number of frequency masks. If its value is zero, no frequency masking will be applied
  freq_mask_param: 32 # Maximum possible length of the frequency mask
  iid_masks: true # Applies iid masks to each of the examples in the batch dimension.
  min_p: 0.05 # minimum proportion of time steps that can be masked. Must be within range [0.0, 1.0]. (Default: -1 which means use fixed number of masks)
  max_p: 0.5 # maximum proportion of time steps that can be masked. Must be within range [0.0, 1.0]. (Default: 1.0)
  zero_masking: false # If true, masked values will be set to zero, otherwise they will be set to the mean value of the input spectrogram


training:
  start_spec_augment_after_n_epochs: 0
  batch_size: 704
  backprop_every: 1
  backwards_every: 1
  max_seq_len: 0
  clip_value: 0.8
  intermediate_loss_weighting: 0.0
  random_seed: [
    53212,
    62334,
    4231, #1
    9643,
    43521,
    6789, #2
    82413,
    1233,
    43422, #3
    12235,
    9877,
    43323, #4
    4232,
    9547,
    11523, #5
    74172,
    1236,
    435324, #6
    82341,
    12343,
    43522, #3
    1235,
    9877,
    4323, #4
    4232,
    82341,
    152333,
    41322, #3
    15235,
    95877,
    43523, #4
    42232,
    43322, #3
    12315,
    98727,
    43213, #4
    423324,
    95447,
    11233, #5
  ]

# size: 512 = batch size 704
# size: 1024 = batch size 352
# size: 2048 = batch size 176
# size: 4096 = batch size 88
# size: 8192 = batch size 44
# size: 16384 = batch size 22
# size: 65536 = batch size 5 
# size: 131072 = batch size 2
# size: 360000 (1 hour) =  batch size 1