model:
  feat_in: 80
  n_layers: 1
  decoder_layers: 10
  d_model: 768
  ctc_loss_weight: 0.0
  acoustic_norm: true
  additional_embeddings: 1
  subsampling_factor: 64
  subsampling_conv_channels: 256
  subsampling: conv_residual
  min_seq_len: 2048
  no_encoder_padding: true
optimizer:
  name: madgrad
  args:
    lr: 0.001
scheduler:
  warmup_steps: 9000
audio_chunking:
  size: 256
  overlap: 0
wandb:
  use: true
  project_name: spotify_enc_dec
  name: hist_64x_decoder
  update_config_with_wandb_id: true
  id: ycqzzwmr
  dir: /mnt/parscratch/users/acp21rjf/wandb_log/
checkpointing:
  dir: /mnt/parscratch/users/acp21rjf/spotify/checkpoints/enc_dec/hist_64x_decoder
  save_every_n_steps: 2000
data:
  path: /mnt/parscratch/users/acp21rjf/spotify/audio_txt_pairs.json
training:
  start_spec_augment_after_n_epochs: -1
  max_epochs: 2
  batch_size: 88
  backprop_every: 1
  backwards_every: 1
  max_seq_len: 0
  clip_value: 0.8
  intermediate_loss_weighting: 0.0
  random_seed: 552268
  dtype: float32
  loss_on_previous: false
  condition_on_previous: true
  use_ctc_history: false
sequence_scheduler:
  increase_every: 2500
  stop_after: 90000
  start_after: 0
  max_sequence_length: 2048
  increase_by_multiplier: 2
  batch_size_multiplier: 1.0
model_class: EncDecSconformerV2
