template_info:
  create: 12 # number of experiments to create
  include_keys: ['model', 'optimizer', 'scheduler', 'audio_chunking', 'wandb', 'checkpointing', 'data', 'training'] #, 'sequence_scheduler'] # keys to include in experiments config
  template_keys: [
    'checkpointing.dir', 
    'wandb.name', 
    'training.random_seed',
    'optimizer.args.lr',
    'scheduler.warmup_steps',
    'audio_chunking.size',
    'training.batch_size',
    'training.backprop_every',
  ] # keys to use to create experiments

model:
  feat_in: 80
  n_layers: 6
  d_model: 768
  n_heads: 6
  head_dim: 128
  dropout_ff: 0.0 # dropout parameters
  dropout_attn: 0.0
  dropout_conv: 0.0
  subsampling_factor: 8 # subsampling parameters
  subsampling: 'dw_striding'
  subsampling_act: 'silu'
  subsampling_conv_channels: 256
  self_condition_subsampling: false
  subsampling_norm_out: false
  conv_kernel_size: 9
  qk_rms_norm: false 
  shift_kvs: false
  self_conditioning: true
  gated_sc: false
  decoder_norm: true
  use_rotary: true
  encoder_mode: 'conformer'
  default_norm: 'layer_norm'
  sandwich_norm: false
  bias_in_ff: false
  checkpoint_every_n_layers: 3

optimizer:
  name: 'madgrad'
  args:
    lr: [
      3.5e-3,
      3.5e-3,
      3.5e-3, #1
      3e-3,
      3e-3,
      3e-3, # 2
      3e-3,
      3e-3,
      3e-3, # 3
      1.1e-3, 
      1.1e-3, 
      1.1e-3, # 4
    ]

scheduler:
  warmup_steps: [
    1500,
    1500,
    1500, #1
    9000,
    9000,
    9000, #2
    9000,
    9000,
    9000, #3
    9000,
    9000,
    9000, #4
  ]

audio_chunking: # 360000 (max = 1 hour)
  size: [
    512,
    512,
    512,
    1024,
    1024,
    1024,
    2048,
    2048,
    2048,
    4096,
    4096,
    4096,
  ]
  overlap: 0 # not using currently...

# sequence_scheduler:
#   increase_every: 5000
#   stop_after: 90000
#   start_after: 0
#   max_sequence_length: [
#     2048,
#     2048,
#     2048,
#     4096,
#     4096,
#     4096,
#     8192,
#     8192,
#     8192,
#     16384,
#     16384,
#     16384,
#     32768,
#     32768,
#     32768,
#     360000,
#     360000,
#     360000,
#   ]
#   increase_by_multiplier: 2
#   batch_size_multiplier: 0.5
#   interpolate_rotary: false

wandb:
  use: true
  project_name: "spotify_long_context"
  name: [ 
    'n_512_rp_1',
    'n_512_rp_2',
    'n_512_rp_3',
    'n_1024_rp_1',
    'n_1024_rp_2',
    'n_1024_rp_3',
    'n_2048_rp_1',
    'n_2048_rp_2',
    'n_2048_rp_3',
    'n_4096_rp_1',
    'n_4096_rp_2',
    'n_4096_rp_3',
  ]
  id: "" # leave empty if not resuming a previous run

checkpointing:
  dir: [
    '/mnt/parscratch/users/acp21rjf/spotify/checkpoints_rp/n_512_rp_1',
    '/mnt/parscratch/users/acp21rjf/spotify/checkpoints_rp/n_512_rp_2',
    '/mnt/parscratch/users/acp21rjf/spotify/checkpoints_rp/n_512_rp_3',
    '/mnt/parscratch/users/acp21rjf/spotify/checkpoints_rp/n_1024_rp_1',
    '/mnt/parscratch/users/acp21rjf/spotify/checkpoints_rp/n_1024_rp_2',
    '/mnt/parscratch/users/acp21rjf/spotify/checkpoints_rp/n_1024_rp_3',
    '/mnt/parscratch/users/acp21rjf/spotify/checkpoints_rp/n_2048_rp_1',
    '/mnt/parscratch/users/acp21rjf/spotify/checkpoints_rp/n_2048_rp_2',
    '/mnt/parscratch/users/acp21rjf/spotify/checkpoints_rp/n_2048_rp_3',
    '/mnt/parscratch/users/acp21rjf/spotify/checkpoints_rp/n_4096_rp_1',
    '/mnt/parscratch/users/acp21rjf/spotify/checkpoints_rp/n_4096_rp_2',
    '/mnt/parscratch/users/acp21rjf/spotify/checkpoints_rp/n_4096_rp_3',
  ]
  save_every_n_steps: 2000

# full data: #'/mnt/parscratch/users/acp21rjf/spotify/audio_txt_pairs.json'
# 25% of corpus: '/users/acp21rjf/long-context-asr/reduced_pairs.json'
data:
  path: '/mnt/parscratch/users/acp21rjf/spotify/audio_txt_pairs.json'
  
training:
  batch_size: [
    352,
    352,
    352, #1
    352,
    352,
    352, #2
    176,
    176,
    176, #3
    88,
    88,
    88, #4
  ]
  backprop_every: [
    2,
    2,
    2, #1
    1,
    1,
    1, #2
    1, 
    1,
    1, #3
    1,
    1,
    1, #4
  ]
  backwards_every: 1
  max_seq_len: 0
  clip_value: 0.8
  intermediate_loss_weighting: 0.0
  random_seed: [
    1234,
    6432,
    9876, #1
    9643,
    4321,
    6789, #2
    8241,
    1233,
    4322, #3
    1235,
    9877,
    4323, #4
  ]

# size: 512 = batch size 704
# size: 1024 = batch size 352
# size: 2048 = batch size 176
# size: 4096 = batch size 88
# size: 8192 = batch size 44
# size: 16384 = batch size 22
# size: 65536 = batch size 5 
# size: 131072 = batch size 2
# size: 360000 (1 hour) =  batch size 1