template_info:
  create: 3 # number of experiments to create
  include_keys: ['model', 'optimizer', 'scheduler', 'audio_chunking', 'wandb', 'checkpointing', 'data', 'training'] # keys to include in experiments config
  template_keys: ['checkpointing.dir', 'wandb.name', optimizer.args.lr, audio_chunking.size, training.batch_size, training.backprop_every] # keys to use to create experiments

model:
  feat_in: 80
  n_layers: 6
  d_model: 768
  n_heads: 6
  head_dim: 128
  dropout_ff: 0.0 # dropout parameters
  dropout_attn: 0.0
  dropout_conv: 0.0
  subsampling_factor: 8 # subsampling parameters
  subsampling: 'dw_striding'
  subsampling_act: 'silu'
  subsampling_conv_channels: 256
  self_condition_subsampling: false
  subsampling_norm_out: false
  conv_kernel_size: 9
  qk_rms_norm: false 
  shift_kvs: false
  self_conditioning: true
  gated_sc: false
  decoder_norm: true
  use_rotary: true
  encoder_mode: 'conformer'
  history_vector: false
  default_norm: 'rms_norm'
  sandwich_norm: false
  bias_in_ff: false
  checkpoint_every_n_layers: 0

optimizer:
  name: 'madgrad'
  args:
    lr: [
      4e-3, #1
      5e-3, #2
      6e-3, #3
    ]

scheduler:
  warmup_steps: 3000

audio_chunking: # 360000 (max = 1 hour)
  size: [
    2048, #1
    2048, #2
    2048, #3
    ]
  overlap: 0 # not using currently...

wandb:
  use: true
  project_name: "spotify_long_context"
  name: [ 
    '2048_4e3', #1
    '2048_5e3', #2
    '2048_6e3', #3
  ]
  id: "" # leave empty if not resuming a previous run

checkpointing:
  dir: [
    '/mnt/parscratch/users/acp21rjf/spotify/checkpoints/2048_4e3', #1
    '/mnt/parscratch/users/acp21rjf/spotify/checkpoints/2048_5e3', #2
    '/mnt/parscratch/users/acp21rjf/spotify/checkpoints/2048_6e3', #3
    
  ]
  save_every_n_steps: 2000

# full data: #'/mnt/parscratch/users/acp21rjf/spotify/audio_txt_pairs.json'
# 25% of corpus: '/users/acp21rjf/long-context-asr/reduced_pairs.json'
data:
  path: '/mnt/parscratch/users/acp21rjf/spotify/audio_txt_pairs.json'
  
training:
  batch_size: [
    176, #1
    176, #2
    176, #3
  ]
  backprop_every: [
    1, #1
    1, #2
    1, #3
  ]
  max_seq_len: 0
  clip_value: 0.8
  intermediate_loss_weighting: 0.0

# size: 1024 = batch size 352
# size: 2048 = batch size 176
# size: 4096 = batch size 88
# size: 8192 = batch size 44
# size: 16384 = batch size 22
# size: 65536 = batch size 5 
# size: 131072 = batch size 2
# size: 360000 (1 hour) =  batch size 1