template_info:
  create: 6 # number of experiments to create
  include_keys: ['model', 'optimizer', 'scheduler', 'audio_chunking', 'wandb', 'checkpointing', 'data', 'training'] # keys to include in experiments config
  template_keys: [
    'checkpointing.dir', 
    'wandb.name', 
    'optimizer.args.momentum',
  ] # keys to use to create experiments

model:
  feat_in: 80
  n_layers: 6
  d_model: 768
  n_heads: 12
  head_dim: 64
  dropout_ff: 0.0
  dropout_attn: 0.0
  dropout_conv: 0.0
  subsampling_factor: 4
  transformer: true
  subsampling: dw_striding
  subsampling_act: silu
  subsampling_conv_channels: -1
  self_condition_subsampling: false
  subsampling_norm_out: false
  conv_kernel_size: 9
  self_conditioning: false
  gated_sc: false
  decoder_norm: true
  use_rotary: true
  default_norm: layer_norm
  sandwich_norm: false
  bias_in_ff: false
  checkpoint_every_n_layers: 0 
  flash_attn: true

optimizer:
  name: madgrad
  args:
    lr: 3e-4
    momentum: [0.7, 0.8, 0.85, 0.88, 0.9, 0.95]

scheduler:
  warmup_steps: 2500

audio_chunking:
  size: 2048
  overlap: 0

# sequence_scheduler:
#   increase_every: 5000
#   stop_after: 90000
#   start_after: 0
#   max_sequence_length: 16384
#   increase_by_multiplier: 2
#   batch_size_multiplier: 0.5

# 512:0
# 1024:4000
# 2048: 14000
# 4096: 24000
# 8192: 34000
# 16384: 44000
# 32768: 54000
# 65536: 64000
# 131072: 74000
# 262144: 84000
# 360000: 90000



wandb:
  use: true
  project_name: spotify_long_context
  name: [
    'no_ds_no_conv_momentum_0p7',
    'no_ds_no_conv_momentum_0p8',
    'no_ds_no_conv_momentum_0p85',
    'no_ds_no_conv_momentum_0p88',
    'no_ds_no_conv_momentum_0p9',
    'no_ds_no_conv_momentum_0p95',
  ]
  id: '' #zhmi8ijr

checkpointing:
  dir: [
      '/mnt/parscratch/users/acp21rjf/spotify/checkpoints/no_ds_no_conv_momentum_0p7',
      '/mnt/parscratch/users/acp21rjf/spotify/checkpoints/no_ds_no_conv_momentum_0p8',
      '/mnt/parscratch/users/acp21rjf/spotify/checkpoints/no_ds_no_conv_momentum_0p85',
      '/mnt/parscratch/users/acp21rjf/spotify/checkpoints/no_ds_no_conv_momentum_0p88',
      '/mnt/parscratch/users/acp21rjf/spotify/checkpoints/no_ds_no_conv_momentum_0p9',
      '/mnt/parscratch/users/acp21rjf/spotify/checkpoints/no_ds_no_conv_momentum_0p95',

    ]
  save_every_n_steps: 2000

data:
  path: /mnt/parscratch/users/acp21rjf/spotify/audio_txt_pairs.json

training:
  start_spec_augment_after_n_epochs: -1 # -1 to disable
  max_epochs: 1
  batch_size: 132
  backprop_every: 1
  backwards_every: 1
  max_seq_len: 0
  clip_value: 1.0
  intermediate_loss_weighting: 0.0
  random_seed: 14349


# size: 512 = batch size 704
# size: 1024 = batch size 352
# size: 2048 = batch size 176
# size: 4096 = batch size 88
# size: 8192 = batch size 44
# size: 16384 = batch size 22
# size: 65536 = batch size 5 
# size: 131072 = batch size 2
# size: 360000 (1 hour) =  batch size 1