model_class: StreamingDecoderASR

model:
  feat_in: 80
  n_layers: 14
  d_model: 768
  n_heads: 6
  expansion_factor: 4
  dropout_ff: 0.0
  dropout_attn: 0.0
  subsampling_factor: 8
  subsampling: dw_striding
  subsampling_act: silu
  subsampling_conv_channels: 256
  subsampling_norm_out: true
  decoder_norm: true
  previous_token_dropout: 0.05

optimizer:
  name: madgrad
  args:
    lr: 2.5e-3

scheduler:
  warmup_steps: 4000

audio_chunking:
  size: 512
  overlap: 0

streaming:
  delay_seconds: 2.0
  buffer_seconds: 0.25

wandb:
  use: true
  project_name: spotify_long_context
  name: streaming_decoder_asr_100m
  id: ""
  dir: /mnt/parscratch/users/acp21rjf/wandb_log/

checkpointing:
  dir: /mnt/parscratch/users/acp21rjf/spotify/streaming_decoder_asr_100m
  save_every_n_steps: 2000

data:
  path: /mnt/parscratch/users/acp21rjf/spotify/audio_txt_pairs.json

training:
  tokenizer_path: lcasr/artifacts/tokenizer.model
  batch_size: 704
  backprop_every: 1
  max_epochs: 9
  clip_value: 0.8
  dtype: bfloat16
  random_seed: 6433
