global:
  root_path: /mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb/n_seq_sched_
  name: rb_n_seq_sched
  overlap_ratio: 0.875
  window_len: 2048
  seq_len: 360000
  checkpoint: step_105360.pt
  description: "rotary base 90M param model, decoding using windowed attention, analysis on the effect of tts context beyond a buffer of normal context"
  

models:

  # - name: ${global.name}_buffer-${.args.buffer_size}_window-${global.window_len}_seq-${.seq_len}
  #   repeat: 1
  #   seq_len: ${global.seq_len}
  #   overlap_ratio: ${global.overlap_ratio}
  #   path: ${global.root_path}${.seq_len}_rp_${.repeat}/${global.checkpoint}
  #   description: ${global.description}
  #   args:
  #     buffer_size: 1
  # - name: ${global.name}_buffer-${.args.buffer_size}_window-${global.window_len}_seq-${.seq_len}
  #   repeat: 2
  #   seq_len: ${global.seq_len}
  #   overlap_ratio: ${global.overlap_ratio}
  #   path: ${global.root_path}${.seq_len}_rp_${.repeat}/${global.checkpoint}
  #   description: ${global.description}
  #   args:
  #     buffer_size: 1
  # - name: ${global.name}_buffer-${.args.buffer_size}_window-${global.window_len}_seq-${.seq_len}
  #   repeat: 3
  #   seq_len: ${global.seq_len}
  #   overlap_ratio: ${global.overlap_ratio}
  #   path: ${global.root_path}${.seq_len}_rp_${.repeat}/${global.checkpoint}
  #   description: ${global.description}
  #   args:
  #     buffer_size: 1

  # - name: ${global.name}_buffer-${.args.buffer_size}_window-${global.window_len}_seq-${.seq_len}
  #   repeat: 1
  #   seq_len: ${global.seq_len}
  #   overlap_ratio: ${global.overlap_ratio}
  #   path: ${global.root_path}${.seq_len}_rp_${.repeat}/${global.checkpoint}
  #   description: ${global.description}
  #   args:
  #     buffer_size: 2
  # - name: ${global.name}_buffer-${.args.buffer_size}_window-${global.window_len}_seq-${.seq_len}
  #   repeat: 2
  #   seq_len: ${global.seq_len}
  #   overlap_ratio: ${global.overlap_ratio}
  #   path: ${global.root_path}${.seq_len}_rp_${.repeat}/${global.checkpoint}
  #   description: ${global.description}
  #   args:
  #     buffer_size: 2
  # - name: ${global.name}_buffer-${.args.buffer_size}_window-${global.window_len}_seq-${.seq_len}
  #   repeat: 3
  #   seq_len: ${global.seq_len}
  #   overlap_ratio: ${global.overlap_ratio}
  #   path: ${global.root_path}${.seq_len}_rp_${.repeat}/${global.checkpoint}
  #   description: ${global.description}
  #   args:
  #     buffer_size: 2

  # - name: ${global.name}_buffer-${.args.buffer_size}_window-${global.window_len}_seq-${.seq_len}
  #   repeat: 1
  #   seq_len: ${global.seq_len}
  #   overlap_ratio: ${global.overlap_ratio}
  #   path: ${global.root_path}${.seq_len}_rp_${.repeat}/${global.checkpoint}
  #   description: ${global.description}
  #   args:
  #     buffer_size: 4
  - name: ${global.name}_buffer-${.args.buffer_size}_window-${global.window_len}_seq-${.seq_len}
    repeat: 2
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}${.seq_len}_rp_${.repeat}/${global.checkpoint}
    description: ${global.description}
    args:
      buffer_size: 4
  - name: ${global.name}_buffer-${.args.buffer_size}_window-${global.window_len}_seq-${.seq_len}
    repeat: 3
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}${.seq_len}_rp_${.repeat}/${global.checkpoint}
    description: ${global.description}
    args:
      buffer_size: 4


  - name: ${global.name}_buffer-${.args.buffer_size}_window-${global.window_len}_seq-${.seq_len}
    repeat: 1
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}${.seq_len}_rp_${.repeat}/${global.checkpoint}
    description: ${global.description}
    args:
      buffer_size: 8
  - name: ${global.name}_buffer-${.args.buffer_size}_window-${global.window_len}_seq-${.seq_len}
    repeat: 2
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}${.seq_len}_rp_${.repeat}/${global.checkpoint}
    description: ${global.description}
    args:
      buffer_size: 8
  - name: ${global.name}_buffer-${.args.buffer_size}_window-${global.window_len}_seq-${.seq_len}
    repeat: 3
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}${.seq_len}_rp_${.repeat}/${global.checkpoint}
    description: ${global.description}
    args:
      buffer_size: 8


  - name: ${global.name}_buffer-${.args.buffer_size}_window-${global.window_len}_seq-${.seq_len}
    repeat: 1
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}${.seq_len}_rp_${.repeat}/${global.checkpoint}
    description: ${global.description}
    args:
      buffer_size: 16
  - name: ${global.name}_buffer-${.args.buffer_size}_window-${global.window_len}_seq-${.seq_len}
    repeat: 2
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}${.seq_len}_rp_${.repeat}/${global.checkpoint}
    description: ${global.description}
    args:
      buffer_size: 16
  - name: ${global.name}_buffer-${.args.buffer_size}_window-${global.window_len}_seq-${.seq_len}
    repeat: 3
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}${.seq_len}_rp_${.repeat}/${global.checkpoint}
    description: ${global.description}
    args:
      buffer_size: 16


  - name: ${global.name}_buffer-${.args.buffer_size}_window-${global.window_len}_seq-${.seq_len}
    repeat: 1
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}${.seq_len}_rp_${.repeat}/${global.checkpoint}
    description: ${global.description}
    args:
      buffer_size: 32
  - name: ${global.name}_buffer-${.args.buffer_size}_window-${global.window_len}_seq-${.seq_len}
    repeat: 2
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}${.seq_len}_rp_${.repeat}/${global.checkpoint}
    description: ${global.description}
    args:
      buffer_size: 32
  - name: ${global.name}_buffer-${.args.buffer_size}_window-${global.window_len}_seq-${.seq_len}
    repeat: 3
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}${.seq_len}_rp_${.repeat}/${global.checkpoint}
    description: ${global.description}
    args:
      buffer_size: 32


  - name: ${global.name}_buffer-${.args.buffer_size}_window-${global.window_len}_seq-${.seq_len}
    repeat: 1
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}${.seq_len}_rp_${.repeat}/${global.checkpoint}
    description: ${global.description}
    args:
      buffer_size: 64
  - name: ${global.name}_buffer-${.args.buffer_size}_window-${global.window_len}_seq-${.seq_len}
    repeat: 2
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}${.seq_len}_rp_${.repeat}/${global.checkpoint}
    description: ${global.description}
    args:
      buffer_size: 64
  - name: ${global.name}_buffer-${.args.buffer_size}_window-${global.window_len}_seq-${.seq_len}
    repeat: 3
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}${.seq_len}_rp_${.repeat}/${global.checkpoint}
    description: ${global.description}
    args:
      buffer_size: 64


  - name: ${global.name}_buffer-${.args.buffer_size}_window-${global.window_len}_seq-${.seq_len}
    repeat: 1
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}${.seq_len}_rp_${.repeat}/${global.checkpoint}
    description: ${global.description}
    args:
      buffer_size: 128
  - name: ${global.name}_buffer-${.args.buffer_size}_window-${global.window_len}_seq-${.seq_len}
    repeat: 2
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}${.seq_len}_rp_${.repeat}/${global.checkpoint}
    description: ${global.description}
    args:
      buffer_size: 128
  - name: ${global.name}_buffer-${.args.buffer_size}_window-${global.window_len}_seq-${.seq_len}
    repeat: 3
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}${.seq_len}_rp_${.repeat}/${global.checkpoint}
    description: ${global.description}
    args:
      buffer_size: 128


  - name: ${global.name}_buffer-${.args.buffer_size}_window-${global.window_len}_seq-${.seq_len}
    repeat: 1
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}${.seq_len}_rp_${.repeat}/${global.checkpoint}
    description: ${global.description}
    args:
      buffer_size: 256
  - name: ${global.name}_buffer-${.args.buffer_size}_window-${global.window_len}_seq-${.seq_len}
    repeat: 2
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}${.seq_len}_rp_${.repeat}/${global.checkpoint}
    description: ${global.description}
    args:
      buffer_size: 256
  - name: ${global.name}_buffer-${.args.buffer_size}_window-${global.window_len}_seq-${.seq_len}
    repeat: 3
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}${.seq_len}_rp_${.repeat}/${global.checkpoint}
    description: ${global.description}
    args:
      buffer_size: 256


  - name: ${global.name}_buffer-${.args.buffer_size}_window-${global.window_len}_seq-${.seq_len}
    repeat: 1
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}${.seq_len}_rp_${.repeat}/${global.checkpoint}
    description: ${global.description}
    args:
      buffer_size: 352 # 352 = 352 * 10.24s ~ 1 hour
  - name: ${global.name}_buffer-${.args.buffer_size}_window-${global.window_len}_seq-${.seq_len}
    repeat: 2
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}${.seq_len}_rp_${.repeat}/${global.checkpoint}
    description: ${global.description}
    args:
      buffer_size: 352
  - name: ${global.name}_buffer-${.args.buffer_size}_window-${global.window_len}_seq-${.seq_len}
    repeat: 3
    seq_len: ${global.seq_len}
    overlap_ratio: ${global.overlap_ratio}
    path: ${global.root_path}${.seq_len}_rp_${.repeat}/${global.checkpoint}
    description: ${global.description}
    args:
      buffer_size: 352


args:
  verbose: true
  model_class: SCConformerXL
  save_dataframe_path: './results/tta_beyond_windowbuffer_rb_post_windowed_attn.csv'
  evaluation_mode: windowed_attention
  max_sequence_length: 3600000
  run_eval_with: tts_context_eval
  
datasets:
  - name: earnings22
    splits: [test]